### ISSUE TITLE
Create option to switch branch

### ISSUE THREAD

**Issue by ghost** [lwileczek/k8s-quick-start#1]
## Goal

Implement a way to switch branches of kubespray after it's downloaded. 

### Example
```sh
ansible-playbook -i hosts playbooks/controller/main.yml -e use_branch=release-2.11
```
### Why
Kubernetes is evolving quickly and sometimes it's required to use older versions of k8s to get programs to work.  For example, [kubeflow](https://www.kubeflow.org/) is made to work with k8s 1.14 & 1.15.  [kubeflow requirements](https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements)

**Comment by ghost** [comment]
This should be easy to do with a variable and the [ansible git](https://docs.ansible.com/ansible/latest/modules/git_module.html) module 
check out `version`

**Comment by lwileczek** [comment]
Easy, done.
